{{- if .Capabilities.APIVersions.Has "networking.istio.io/v1alpha3/Gateway" }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: jaeger
  namespace: observability
spec:
  selector:
    istio: gateway
  servers:
    - hosts:
      - 'jaeger.testing.com'
      port:
        name: http
        number: 80
        protocol: HTTP
{{- end }}
