{{- if .Capabilities.APIVersions.Has "networking.istio.io/v1alpha3/VirtualService" }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argo-cd
  namespace: argo-cd
spec:
  hosts:
    - argocd.testing.com
  gateways:
    - argo-cd
  http:
    - route:
        - destination:
            host: argo-cd-argocd-server
            port:
              number: 80
{{- end}}
