apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: self-0
spec:
  project: {{ (.Values.project).name }}
  source:
    path: ikpjg/
    targetRevision: HEAD
    repoURL: https://github.com/Dines97/BaseCluster.git
    helm:
      values: |
        {{- with .Values.favorite }}
        {{ . | nindent 8 }}
        {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd


