project:
  name: system

repoURL: https://github.com/Dines97/BaseCluster.git

argo_cd:
  namespace: argo-cd
  version: 4.10.3
  values: |
    server:
      extraArgs: 
        - --insecure
        {{- if not (.Values.authentication).enable }}
        - --disable-auth
        {{- end }}
      # config:
      #   resource.customizations: |
      #     argoproj.io/Application:
      #       health.lua: |
      #         hs = {}
      #         hs.status = "Progressing"
      #         hs.message = ""
      #         if obj.status ~= nil then
      #           if obj.status.health ~= nil then
      #             hs.status = obj.status.health.status
      #             if obj.status.health.message ~= nil then
      #               hs.message = obj.status.health.message
      #             end
      #           end
      #         end
      #         return hs

argo_rollouts:
  version: 2.16.0
  values: |
    dashboard:
      enabled: true

argo_events:
  version: 2.0.0
  values: |

kiali:
  values: |
    cr:
      create: true
      namespace: istio-system
      spec:
        {{- if not (.Values.authentication).enable }}
        auth:
          strategy: "anonymous"
        {{- end }}
        external_services:
          tracing:
            enabled: true
            in_cluster_url: 'http://jaeger-operator-jaeger-query.jaeger-operator:16685/jaeger'
            use_grpc: true
            url: 'http://my-jaeger-host/jaeger'

metallb:
  enable: true
  values: |
    configInline:
      address-pools:
       - name: default
         protocol: layer2
         addresses:
         - 192.168.49.2-192.168.49.2

jaeger_operator:
  version: 2.33.0
  values: |
    jaeger:
      create: true
      namespace: jaeger
      spec:
        ingress:
          enabled: false
    rbac:
      clusterRole: true

istio:
  version: 1.13.2

cert_manager:
  version: v1.8.0
  values: |
    installCRDs: true

postgresql:
  version: 11.6.25

pgadmin4:
  version: 1.11.0
  values: |
    env:
      email: testing@local.com
      password: SuperSecret

kubeflow:
  version: v1.5.1

authentication:
  enable: false

nameOverride: ""
fullnameOverride: ""
