apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  labels:
    {{- include "ikpjg.labels" . | nindent 4 }}
spec:
  project: {{ (.Values.project).name }}
  source:
    chart: argo-events
    targetRevision: {{ (.Values.argo_events).version }}
    repoURL: https://argoproj.github.io/argo-helm
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-events
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

