apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  labels:
    {{- include "ikpjg.labels" . | nindent 4 }}
spec:
  project: {{ (.Values.project).name }}
  source:
    chart: postgresql
    targetRevision: {{ (.Values.postgresql).version }}
    repoURL: https://charts.bitnami.com/bitnami
  destination:
    server: https://kubernetes.default.svc
    namespace: postgresql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

