apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  labels:
    {{- include "ikpjg.labels" . | nindent 4 }}
spec:
  project: {{ (.Values.project).name }}
  source:
    path: ikpjg/
    targetRevision: HEAD
    repoURL: {{ .Values.repoURL }}
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd

