apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "istio-network.fullname" . }}-jaeger
  namespace: jaeger
  labels:
    {{- include "istio-network.labels" . | nindent 4 }}
spec:
  hosts:
    - jaeger.{{ .Values.domain }}
  gateways:
    - default/istio-network-istio-network
  http:
    - route:
        - destination:
            host: jaeger-operator-jaeger-query
            port: 
              number: 16686

