apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "istio-network.fullname" . }}-kiali
  namespace: istio-system
  labels:
    {{- include "istio-network.labels" . | nindent 4 }}
spec:
  hosts:
    - kiali.{{ .Values.domain }}
  gateways:
    - default/istio-network-istio-network
  http:
    - route:
        - destination:
            host: kiali
            port:
              number: 20001
