apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "istio-network.fullname" . }}-rollouts
  namespace: argo-cd
  labels:
    {{- include "istio-network.labels" . | nindent 4 }}
spec:
  hosts:
    - rollouts.{{ .Values.domain }}
  gateways:
    - default/istio-network
  http:
    - route:
        - destination:
            host: argo-cd-argocd-server
            port:
              number: 80
