apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  labels:
    {{- include "ikpjg.labels" . | nindent 4 }}
spec:
  project: {{ (.Values.project).name }}
  source:
    chart: cert-manager
    targetRevision: {{ (.Values.cert_manager).version }}
    repoURL: https://charts.jetstack.io
    helm:
      values: |
        {{- tpl (.Values.cert_manager).values . | nindent 8 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true


