apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ (.Values.project).name }}
  namespace: argo-cd
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: true
    ignore:
      - kind: ConfigMap
        name: istio-ca-root-cert
