apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali-operator
  labels:
    {{- include "ikpjg.labels" . | nindent 4 }}
spec:
  project: {{ (.Values.project).name }}
  source:
    chart: kiali-operator
    repoURL: https://kiali.org/helm-charts 
    targetRevision: 1.48.0
    helm:
      values: |
        {{- tpl (.Values.kiali).values . | nindent 8 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: kiali-operator

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true



