apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  labels:
    {{- include "ikpjg.labels" . | nindent 4 }}
spec:
  project: {{ (.Values.project).name }}
  source:
    chart: argo-cd
    targetRevision: {{ (.Values.argo_cd).version }}
    repoURL: https://argoproj.github.io/argo-helm
    helm:
      values: |
        {{- tpl (.Values.argo_cd).values . | nindent 8 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


