apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway-0
  labels:
    {{- include "ikpjg.labels" . | nindent 4 }}
spec:
  project: {{ (.Values.project).name }}
  source:
    chart: gateway
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.13.0
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system


